# Run rustfmt with this config (it should be picked up automatically).
version = "Two"
edition = "2021"
max_width = 120
comment_width = 100
match_block_trailing_comma = true
wrap_comments = true
error_on_line_overflow = true
imports_granularity = "Module"

# by default we ignore everything in the repository
# tidy only checks files which are not ignored, each entry follows gitignore style
ignore = []
